database:
  host: 172.26.0.2
  port: 5432
  user: athena
  password: athena
  name: athena
  ssl_mode: disable
  time_zone: Asia/Shanghai
  max_idle_conns: 100
  max_open_conns: 100
service:
  service_name: auth2
  depend_services:
    - name1
    - name2
  host: 0.0.0.0
  port: 8080
  enable_http: true
registry:
  name: test
  ip: 172.26.0.4:8080
  ttl: 5
  entrypoints:
    - 172.26.0.3:2379
  dial_timeout: 5
  depend_services:
    - user